// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXvrn_40qSFJSSOjJRFsM0gaLkOZCH-C8',
    appId: '1:95581424221:web:66dbd7122483f7d0af5bb4',
    messagingSenderId: '95581424221',
    projectId: 'app-taifa',
    authDomain: 'app-taifa.firebaseapp.com',
    databaseURL: 'https://app-taifa-default-rtdb.firebaseio.com',
    storageBucket: 'app-taifa.appspot.com',
    measurementId: 'G-VN366DT7T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQac9S7G9Le9_sNPnywuYdFm_iPamh3Ug',
    appId: '1:95581424221:android:d997adb21bceae02af5bb4',
    messagingSenderId: '95581424221',
    projectId: 'app-taifa',
    databaseURL: 'https://app-taifa-default-rtdb.firebaseio.com',
    storageBucket: 'app-taifa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPUoJavsNRSxXKYdu-RIk4kPOjzzfLok',
    appId: '1:95581424221:ios:676d9bc6ecb4ae3aaf5bb4',
    messagingSenderId: '95581424221',
    projectId: 'app-taifa',
    databaseURL: 'https://app-taifa-default-rtdb.firebaseio.com',
    storageBucket: 'app-taifa.appspot.com',
    iosClientId: '95581424221-tc85iivpu0ql0e1sq46t3iafs3uik1k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTaifaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjPUoJavsNRSxXKYdu-RIk4kPOjzzfLok',
    appId: '1:95581424221:ios:7d89c0ba3483dca2af5bb4',
    messagingSenderId: '95581424221',
    projectId: 'app-taifa',
    databaseURL: 'https://app-taifa-default-rtdb.firebaseio.com',
    storageBucket: 'app-taifa.appspot.com',
    iosClientId: '95581424221-ib8ij2llnmj8pb8fcfs7dfek0c798cag.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTaifaFlutter.RunnerTests',
  );
}
