name: app_taifa_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.12.0
  google_sign_in: ^6.0.0
  cloud_firestore: ^4.12.1
  google_maps_flutter: ^2.5.0
  firebase_core_platform_interface: ^5.0.0 #do i need?
  google_maps: ^6.3.0
  geolocator: ^8.2.1
  fuzzy: <1.0.0
  flutter_dotenv: ^5.1.0
  gsheets: ^0.5.0
  url_launcher: ^6.2.4
  flutter_launcher_icons: ^0.13.1
  file_picker: ^5.0.0
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  image_path: "assets/images/logoTaifa.png"
  android: true
  ios: true
  remove_alpha_ios: true # optional, remove if something breaks

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # Add assets from the images directory to the application.
  assets:
    - assets/images/
    - .env
